/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BooksRouteImport } from './routes/books'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ReadersRouteImport } from './routes/readers'
import { Route as ReadingOrderRouteImport } from './routes/reading-order'
import { Route as TrailersRouteImport } from './routes/trailers'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksSlugRouteImport } from './routes/books.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadersRoute = ReadersRouteImport.update({
  id: '/readers',
  path: '/readers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingOrderRoute = ReadingOrderRouteImport.update({
  id: '/reading-order',
  path: '/reading-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailersRoute = TrailersRouteImport.update({
  id: '/trailers',
  path: '/trailers',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRouteWithChildren
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/readers': typeof ReadersRoute
  '/reading-order': typeof ReadingOrderRoute
  '/trailers': typeof TrailersRoute
  '/books/$slug': typeof BooksSlugRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/readers': typeof ReadersRoute
  '/reading-order': typeof ReadingOrderRoute
  '/trailers': typeof TrailersRoute
  '/books/$slug': typeof BooksSlugRoute
  '/books': typeof BooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/books': typeof BooksRouteWithChildren
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/readers': typeof ReadersRoute
  '/reading-order': typeof ReadingOrderRoute
  '/trailers': typeof TrailersRoute
  '/books/$slug': typeof BooksSlugRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/books'
    | '/contact'
    | '/journal'
    | '/readers'
    | '/reading-order'
    | '/trailers'
    | '/books/$slug'
    | '/books/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/journal'
    | '/readers'
    | '/reading-order'
    | '/trailers'
    | '/books/$slug'
    | '/books'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/books'
    | '/contact'
    | '/journal'
    | '/readers'
    | '/reading-order'
    | '/trailers'
    | '/books/$slug'
    | '/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BooksRoute: typeof BooksRouteWithChildren
  ContactRoute: typeof ContactRoute
  JournalRoute: typeof JournalRoute
  ReadersRoute: typeof ReadersRoute
  ReadingOrderRoute: typeof ReadingOrderRoute
  TrailersRoute: typeof TrailersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readers': {
      id: '/readers'
      path: '/readers'
      fullPath: '/readers'
      preLoaderRoute: typeof ReadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading-order': {
      id: '/reading-order'
      path: '/reading-order'
      fullPath: '/reading-order'
      preLoaderRoute: typeof ReadingOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trailers': {
      id: '/trailers'
      path: '/trailers'
      fullPath: '/trailers'
      preLoaderRoute: typeof TrailersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof BooksRoute
    }
  }
}

interface BooksRouteChildren {
  BooksSlugRoute: typeof BooksSlugRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksSlugRoute: BooksSlugRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BooksRoute: BooksRouteWithChildren,
  ContactRoute: ContactRoute,
  JournalRoute: JournalRoute,
  ReadersRoute: ReadersRoute,
  ReadingOrderRoute: ReadingOrderRoute,
  TrailersRoute: TrailersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
